on: [push, pull_request]

name: ci

jobs:
  check:
    name: Check
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    runs-on: macos-latest
    name: Test (${{ matrix.rust-toolchain }})
    strategy:
      fail-fast: false
      matrix:
        rust-toolchain: [1.39.0, stable, nightly]
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust (${{ matrix.rust-toolchain }})
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust-toolchain }}
          override: true
      - name: Rust Version
        run: rustc -vV
      - name: Set Doctest Env
        if: matrix.rust-toolchain == '1.39.0'
        run: echo 'RUSTDOCFLAGS=--cfg=pass_reuse_doctest' >> $GITHUB_ENV
      - name: Test Debug
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Test Release
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release

  fmt:
    name: Rustfmt
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  doc:
    name: Rustdoc
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: -D warnings
        with:
          command: doc
